### ISSUE TITLE
doesn't work patched 

### ISSUE THREAD

**Issue by SlotthCode** [detectivevoke/hcaptcha-motion-data#1]
it's got patched, you skid. stop being bad skid, grow up.

**Comment by mciem** [comment]
fr only skids are on github no real coders 💯 🔥

**Comment by SlotthCode** [comment]
10000% for real

**Comment by mciem** [comment]
> 
ik im smarter than them 100%

**Comment by SlotthCode** [comment]
me too, I make discord token gens 🔥 💯 😨  best coder on GitHub 🙅 🧢

**Comment by mciem** [comment]
i made HCaptcha Bypass that works in REAL LIFE 💯 🔥 🆓 😮‍💨 i will post it on git tmrw 🥇

**Comment by SlotthCode** [comment]
we are smoking 🚬 that patched pack

**Comment by mciem** [comment]
fr fuck that code 100% skidded

**Comment by SlotthCode** [comment]
> i made HCaptcha Bypass that works in REAL LIFE 💯 🔥 🆓 😮‍💨 i will post it on git tmrw 🥇

OMG 😱 you are proooo. 😨  I should stay away from you 💯 🏃 🚬 :

**Comment by mciem** [comment]
ong 💯 🇫🇷 🇫🇷 🔥

**Comment by SlotthCode** [comment]
we might as well hack voke 🖥️  💯 🚬 🏃  he skid 😨 and bad skid 😱

**Comment by mciem** [comment]
good idea im turning on my botnet from wish 😱💯 🚬 🏃💯 🚬 🏃

**Comment by mciem** [comment]
**Starting Hack Client...
1000 Bots are Online
Finding Detective Voke Email
Found email: ilikeslotthandmciem@gmail.com 
Finding Password...
Found Password: IAmASkidIDon'tKnowPython123!!
Hack Done.. 💯**

**Comment by SlotthCode** [comment]
I am turning on my bot net from eBay, it was free 😱💯 🚬 🏃💯 🚬 🏃 😱💯 🚬 🏃💯 🚬 🏃 😱💯 🚬 🏃💯 🚬 🏃

**Comment by SlotthCode** [comment]
We should hack TrixTM soon  😱💯 🚬 🏃💯 🚬 🏃

**Comment by mciem** [comment]
good idea
💯 💯 💯 💯

**Comment by SlotthCode** [comment]
not fixed
